version: "3"

services:
  redis:
    container_name: redis
    image: redis:7.2
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /etc/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /redis/data:/data
    ports:
      - "6379:6379"

  was-blue:
    container_name: was-blue
    image: suhyun9252/dandi-be:GITHUB_SHA
    restart: always
    volumes:
      - /dandi/logs:/app/logs  # log 보존
    ports:
      - "3000:3000"
    env_file:
      - /dandi/.env
    depends_on:
      - redis
  
  frontend-blue:
    container_name: frontend-blue
    image: suhyun9252/dandi-fe:GITHUB_SHA
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /dandi/nginx/dandi-blue.conf:/etc/nginx/conf.d/dandi.conf
      - /var/log/nginx/blue:/var/log/nginx
    depends_on:
      - was-blue