version: "3"

services:
  was-green:
    container_name: was-green
    image: suhyun9252/dandi-be:GITHUB_SHA
    restart: always
    volumes:
      - /dandi/logs:/app/logs  # log 보존
    ports:
      - "3001:3001"
    env_file:
      - /dandi/.env

  frontend-green:
    container_name: frontend-green
    image: suhyun9252/dandi-fe:GITHUB_SHA
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - /dandi/nginx/dandi-green.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx/green:/var/log/nginx
    depends_on:
      - was-green